name: "fcp-back-end-app"
services:
    db:
        build:
            context: ../DB
            dockerfile: ../dev-ops/dockerfiles/db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ../DB/data:/var/lib/mysql:rw
            - ../LOGS/db-logs:/var/log/mysql:rw
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD"]
            start_period: 3s
            interval: 1s
            timeout: 1s
            retries: 1000
    cache:
        build:
            context: ../CACHE
            dockerfile: ../dev-ops/dockerfiles/cache
        ports:
            - "6379:6379"
        volumes:
            - ../CACHE/data:/var/lib/cache:rw
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping"]
            start_period: 3s
            interval: 1s
            timeout: 1s
            retries: 1000
    app:
        build:
            context: ../MAIN
            dockerfile: ../dev-ops/dockerfiles/app
        environment:
            - DB_HOST=:)
            - DB_PORT=:)
            - CACHE_HOST=:)
            - CACHE_PORT=:)
            - LOGGER_SINK=app-logs/fastapi.log
            - GOOGLE_OAUTH_CLIENT_ID=:)
            - GOOGLE_OAUTH_CLIENT_SECRET=:)
            - BACK_END_HOST=http://localhost:8000
            - FRONT_END_HOST=http://localhost:3000
        ports:
            - "8000:8000"
        volumes:
            - ../LOGS/app-logs:/app-logs:rw
        depends_on:
            db:
                condition: service_healthy
            cache:
                condition: service_healthy